'use client';

import { useEffect, useState } from 'react';
import { Activity, BarChart3, CheckCircle2, FileText, Sparkles, Users } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

export default function AdminAnalyticsPage() { const [stats, setStats] = useState<{ users: number; documents: number; templates: number; ai_requests_30d: number } | null>(null); useEffect(() => { apiFetch<typeof stats>('/api/admin/stats').then((data) => setStats(data ? { users: data.users, documents: data.documents, templates: data.templates, ai_requests_30d: data.ai_requests_30d } : null)); }, []); const metrics = [{ label: 'Workspace members', value: stats?.users, icon: Users, color: 'text-forest' }, { label: 'Documents created', value: stats?.documents, icon: FileText, color: 'text-gold' }, { label: 'AI operations', value: stats?.ai_requests_30d, icon: Sparkles, color: 'text-amber-600' }]; return <div className="space-y-8"><div><p className="eyebrow">Administration</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Analytics</h1><p className="mt-2 text-sm text-muted">Aggregated service signals. Private document content is intentionally excluded.</p></div><div className="grid gap-4 md:grid-cols-3">{metrics.map((metric) => <Card key={metric.label} className="p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted">{metric.label}</p><metric.icon className={`h-5 w-5 ${metric.color}`} /></div>{stats ? <p className="mt-4 text-3xl font-extrabold">{metric.value}</p> : <Skeleton className="mt-4 h-9 w-16" />}</Card>)}</div><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Service health</h2><p className="mt-1 text-sm text-muted">A simple view of the current deployment.</p></div><Badge variant="success"><CheckCircle2 className="h-3.5 w-3.5" /> Operational</Badge></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{[['API', 'FastAPI routes and authorization', Activity], ['AI provider', 'Configured mode is reported without secrets', Sparkles], ['Database', 'SQLAlchemy session and migrations', BarChart3]].map(([name, text, Icon]) => <div key={name as string} className="rounded-xl bg-[var(--background)] p-4"><Icon className="h-4 w-4 text-emerald-500" /><p className="mt-3 text-sm font-bold">{name as string}</p><p className="mt-1 text-xs leading-5 text-muted">{text as string}</p></div>)}</div></Card><Card className="p-6"><h2 className="text-lg font-bold">Usage trend</h2><p className="mt-1 text-sm text-muted">Illustrative chart frame. Connect your production telemetry provider for verified longitudinal reporting.</p><div className="mt-8 flex h-52 items-end gap-2">{Array.from({ length: 30 }).map((_, index) => <div key={index} className="flex-1 rounded-t-md bg-forest/15" style={{ height: `${18 + ((index * 29) % 70)}%` }} />)}</div><div className="mt-3 flex justify-between text-[10px] text-muted"><span>30 days ago</span><span>Today</span></div></Card></div>; }
