from __future__ import annotations

# Kept verbatim so the long-standing `professional_review_notice` contract never changes.
PROFESSIONAL_REVIEW_NOTICE = (
    "This automated review is not a legal opinion and cannot determine validity, enforceability, "
    "safety, or compliance."
)

AUTOMATED_ANALYSIS_DISCLAIMER = (
    "Automated analysis is not legal advice. LegalEase does not practise law, and this review is "
    "produced by automated software. It cannot determine whether a document is valid, "
    "enforceable, safe, or legally compliant, and it does not confirm that any clause will be "
    "upheld by a court. Findings are prompts for questions to raise with a qualified lawyer who "
    "is admitted in the relevant jurisdiction. Do not sign, rely on, or act on this review "
    "without independent professional advice."
)

ASSISTANT_DISCLAIMER = (
    "General legal information only, not legal advice. Laws and procedures vary by jurisdiction; "
    "consult a qualified lawyer about your specific situation."
)

CLAUSE_ANSWER_DISCLAIMER = (
    "This explanation is general legal information generated by automated software, not legal "
    "advice, and it cannot determine enforceability or legal compliance. Confirm any point with "
    "a qualified lawyer before acting on it."
)

REPORT_DISCLAIMER = (
    "This review report was generated automatically by LegalEase. It is not legal advice and "
    "cannot determine the validity, enforceability, safety, or legal compliance of the reviewed "
    "document. Statuses recorded by the reviewer are working notes, not legal conclusions. "
    "Obtain advice from a qualified lawyer before signing or relying on the document."
)

__all__ = [
    "ASSISTANT_DISCLAIMER",
    "AUTOMATED_ANALYSIS_DISCLAIMER",
    "CLAUSE_ANSWER_DISCLAIMER",
    "PROFESSIONAL_REVIEW_NOTICE",
    "REPORT_DISCLAIMER",
]
