from __future__ import annotations

from copy import deepcopy
from typing import Any


def field(
    name: str,
    label: str,
    field_type: str = "text",
    required: bool = False,
    placeholder: str = "",
    help_text: str = "",
    options: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "label": label,
        "type": field_type,
        "required": required,
        "placeholder": placeholder,
        "help": help_text,
        "options": options or [],
    }


def definition(
    slug: str,
    name: str,
    category: str,
    description: str,
    estimated_time: str,
    fields: list[dict[str, Any]],
    sections: list[str],
    instructions: str,
) -> dict[str, Any]:
    return {
        "slug": slug,
        "name": name,
        "category": category,
        "description": description,
        "estimated_time": estimated_time,
        "fields": fields,
        "sections": sections,
        "generation_instructions": instructions,
        "disclaimer": "This template is an AI-assisted starting point and is not legal advice or a guarantee of enforceability.",
    }


TEMPLATE_DEFINITIONS: list[dict[str, Any]] = [
    definition(
        "mutual-nda",
        "Mutual Non-Disclosure Agreement",
        "Business",
        "Protect confidential information shared between two parties during a business discussion.",
        "5–10 minutes",
        [
            field(
                "document_title",
                "Document title",
                required=True,
                placeholder="Mutual NDA — Project Atlas",
            ),
            field("disclosing_party", "Disclosing party", required=True),
            field("receiving_party", "Receiving party", required=True),
            field("effective_date", "Effective date", "date", True),
            field(
                "purpose",
                "Purpose of disclosure",
                "textarea",
                True,
                "Describe the business purpose",
            ),
            field(
                "term",
                "Confidentiality term",
                "select",
                False,
                options=["1 year", "2 years", "3 years", "5 years", "Perpetual for trade secrets"],
            ),
            field("governing_law", "Governing law", required=True),
            field("email", "Notice email", "email", False),
        ],
        [
            "Purpose",
            "Definition of confidential information",
            "Use and protection",
            "Exclusions",
            "Term and return",
            "General terms",
            "Signatures",
        ],
        "Create a balanced mutual NDA. Define confidential information clearly, include customary exclusions, require reasonable safeguards, and make return or deletion obligations practical. Do not invent trade-secret status or remedies.",
    ),
    definition(
        "partnership-agreement",
        "Partnership Agreement",
        "Business",
        "Set out contributions, responsibilities, decision-making, and ownership for a business partnership.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("partner_one", "First partner", required=True),
            field("partner_two", "Second partner", required=True),
            field("business_name", "Business name", required=True),
            field("effective_date", "Effective date", "date", True),
            field("contributions", "Capital or other contributions", "textarea", True),
            field(
                "profit_loss",
                "Profit and loss sharing",
                "select",
                True,
                options=["Equal", "Custom percentages", "Salary plus percentages"],
            ),
            field("decision_process", "Decision-making process", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Business and purpose",
            "Contributions",
            "Management and decisions",
            "Profits, losses, and distributions",
            "Intellectual property",
            "Exit and dispute resolution",
            "General terms",
        ],
        "Draft a practical partnership agreement with clear contribution, governance, ownership, exit, and dispute mechanics. Ask the parties to replace placeholders and align the agreement with any separate founder or IP documents.",
    ),
    definition(
        "founders-agreement",
        "Founders Agreement",
        "Business",
        "Document the commitments, equity intent, responsibilities, and decisions of company founders.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("company_name", "Company name", required=True),
            field("founders", "Founders and roles", "textarea", True),
            field("formation_date", "Formation date", "date", False),
            field("equity_plan", "Equity and vesting plan", "textarea", True),
            field("time_commitment", "Time commitment", "textarea", True),
            field("ip_assignment", "Intellectual property assignment", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Founders and company",
            "Roles and commitments",
            "Equity and vesting",
            "Intellectual property",
            "Confidentiality",
            "Decision-making and departures",
            "General terms",
        ],
        "Create a founder agreement that separates business promises from any later equity grant. Highlight the need for jurisdiction-specific securities and tax advice. Include vesting and IP assignment only as clearly stated commercial intentions.",
    ),
    definition(
        "memorandum-of-understanding",
        "Memorandum of Understanding",
        "Business",
        "Record exploratory discussions and proposed next steps without unintentionally creating a binding contract.",
        "5–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("party_one", "First party", required=True),
            field("party_two", "Second party", required=True),
            field("date", "Date", "date", True),
            field("proposal", "Proposed arrangement", "textarea", True),
            field("scope", "Scope under discussion", "textarea", True),
            field("binding_terms", "Binding terms, if any", "textarea", False),
            field("next_steps", "Next steps and timeline", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Purpose and status",
            "Parties",
            "Proposal",
            "Scope",
            "Commercial points",
            "Next steps",
            "Non-binding and confidentiality",
            "Signatures",
        ],
        "Make the non-binding status prominent, identify any provisions that are expressly binding, and avoid language that accidentally promises exclusivity, exclusivity, or a final transaction.",
    ),
    definition(
        "business-service-agreement",
        "Business Service Agreement",
        "Business",
        "Define ongoing services, deliverables, fees, service levels, and responsibilities for a business engagement.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("provider", "Service provider", required=True),
            field("client", "Client", required=True),
            field("effective_date", "Effective date", "date", True),
            field("services", "Services", "textarea", True),
            field("deliverables", "Deliverables and milestones", "textarea", True),
            field("fees", "Fees and expenses", "textarea", True),
            field(
                "payment_terms",
                "Payment terms",
                "select",
                True,
                options=["Due on receipt", "Net 15", "Net 30", "Net 45"],
            ),
            field("termination", "Termination rights", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Services",
            "Deliverables and acceptance",
            "Fees and payment",
            "Term and termination",
            "Confidentiality and data",
            "Independent contractor status",
            "Liability and general terms",
        ],
        "Draft a services agreement with measurable deliverables, acceptance criteria, invoice mechanics, change control, and balanced termination language. Do not promise an outcome that the input does not support.",
    ),
    definition(
        "independent-contractor-agreement",
        "Independent Contractor Agreement",
        "Business",
        "Set out a project-based independent contractor relationship and ownership of work product.",
        "8–12 minutes",
        [
            field("document_title", "Document title", required=True),
            field("contractor", "Contractor", required=True),
            field("client", "Client", required=True),
            field("project", "Project or services", "textarea", True),
            field("start_date", "Start date", "date", True),
            field("completion_date", "Expected completion", "date", False),
            field("fee", "Fee", "number", True, placeholder="2500"),
            field(
                "payment_schedule",
                "Payment schedule",
                "select",
                True,
                options=["Upfront", "50/50", "Monthly", "On completion", "Custom"],
            ),
            field("ip_terms", "Work product ownership", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Services and project",
            "Compensation",
            "Work product and rights",
            "Confidentiality",
            "Independent status",
            "Termination",
            "General terms",
        ],
        "Describe the contractor relationship carefully without making employment-status conclusions. Address scope, payment, independent status, work product, confidentiality, and termination in plain language.",
    ),
    definition(
        "employment-agreement",
        "Employment Agreement",
        "Employment",
        "Document an employment relationship, compensation, duties, and termination framework.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("employer", "Employer", required=True),
            field("employee", "Employee", required=True),
            field("job_title", "Job title", required=True),
            field("start_date", "Start date", "date", True),
            field("work_location", "Work location", required=True),
            field("salary", "Base salary", "number", True, placeholder="75000"),
            field(
                "pay_schedule",
                "Pay schedule",
                "select",
                True,
                options=["Weekly", "Biweekly", "Monthly"],
            ),
            field("benefits", "Benefits summary", "textarea", False),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Position and duties",
            "Compensation and benefits",
            "Work location and policies",
            "Confidentiality and IP",
            "Term and termination",
            "General terms",
            "Signatures",
        ],
        "Create a jurisdiction-aware employment agreement without promising statutory compliance. Flag mandatory local terms for professional review, especially termination, leave, benefits, and restrictive covenants.",
    ),
    definition(
        "offer-letter",
        "Offer Letter",
        "Employment",
        "Summarize an employment offer, compensation, start date, and conditions clearly.",
        "5–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("employer", "Employer", required=True),
            field("candidate", "Candidate", required=True),
            field("job_title", "Job title", required=True),
            field("start_date", "Proposed start date", "date", True),
            field("salary", "Annual salary", "number", True, placeholder="90000"),
            field("bonus", "Bonus or variable compensation", "textarea", False),
            field("benefits", "Benefits", "textarea", False),
            field("conditions", "Conditions of offer", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Offer summary",
            "Compensation",
            "Start date and location",
            "Conditions",
            "Confidentiality and contingencies",
            "Acceptance",
            "Signatures",
        ],
        "Use a clear offer-letter structure. Separate discretionary benefits from guaranteed terms and state that the letter is subject to employment documentation and applicable law.",
    ),
    definition(
        "termination-letter",
        "Termination Letter",
        "Employment",
        "Communicate an employment decision while preserving required legal and process safeguards.",
        "5–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("employer", "Employer", required=True),
            field("employee", "Employee", required=True),
            field("decision_date", "Decision date", "date", True),
            field("last_day", "Last working day", "date", True),
            field("reason", "Reason or transition framing", "textarea", True),
            field("final_pay", "Final pay arrangements", "textarea", True),
            field("benefits", "Benefits and property arrangements", "textarea", False),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Decision",
            "Transition and final pay",
            "Benefits and property",
            "Confidentiality and references",
            "Contact and acknowledgement",
        ],
        "Draft a factual, respectful letter and avoid unsupported accusations. Include placeholders for jurisdiction-specific notice, severance, and benefits language rather than making legal conclusions.",
    ),
    definition(
        "confidentiality-agreement",
        "Confidentiality Agreement",
        "Employment",
        "Protect confidential information shared by an employee, contractor, or volunteer.",
        "5–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("disclosing_party", "Disclosing party", required=True),
            field("receiving_party", "Receiving party", required=True),
            field(
                "relationship",
                "Relationship",
                "select",
                True,
                options=["Employee", "Contractor", "Volunteer", "Other"],
            ),
            field("effective_date", "Effective date", "date", True),
            field("information", "Protected information", "textarea", True),
            field(
                "term",
                "Protection period",
                "select",
                True,
                options=[
                    "During relationship",
                    "1 year after",
                    "3 years after",
                    "Perpetual for trade secrets",
                ],
            ),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Purpose",
            "Protected information",
            "Permitted use",
            "Safeguards and exclusions",
            "Return and deletion",
            "Duration",
            "General terms",
            "Signatures",
        ],
        "Keep the agreement specific to the actual relationship. Include reasonable exclusions, authorized disclosures, and a practical process for return or deletion.",
    ),
    definition(
        "residential-rental-agreement",
        "Residential Rental Agreement",
        "Property",
        "Set out the key terms of a residential tenancy for a home or apartment.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("landlord", "Landlord", required=True),
            field("tenant", "Tenant or tenants", required=True),
            field("property_address", "Property address", "textarea", True),
            field("start_date", "Lease start", "date", True),
            field("end_date", "Lease end", "date", False),
            field("rent", "Monthly rent", "number", True, placeholder="2400"),
            field("deposit", "Security deposit", "number", True),
            field("utilities", "Utilities and services", "textarea", True),
            field("rules", "Property rules", "textarea", False),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Parties and premises",
            "Term",
            "Rent and deposit",
            "Utilities and condition",
            "Use and maintenance",
            "Entry, termination, and notices",
            "General terms",
            "Signatures",
        ],
        "Draft a practical residential tenancy outline and explicitly flag local disclosure, rent, deposit, eviction, and notice requirements for legal review. Do not imply compliance with local law.",
    ),
    definition(
        "lease-agreement",
        "Lease Agreement",
        "Property",
        "Cover a commercial or other property lease with core financial and operational terms.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("landlord", "Landlord", required=True),
            field("tenant", "Tenant", required=True),
            field("property_address", "Leased premises", "textarea", True),
            field("lease_term", "Lease term", "textarea", True),
            field("base_rent", "Base rent", "number", True),
            field("escalation", "Rent increases", "textarea", False),
            field("improvements", "Improvements and alterations", "textarea", False),
            field("permitted_use", "Permitted use", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Premises and permitted use",
            "Term",
            "Rent and additional charges",
            "Improvements",
            "Maintenance and insurance",
            "Default and remedies",
            "Surrender and general terms",
        ],
        "Use a general property-lease framework. Keep property-specific and regulatory obligations as clearly marked review points rather than inventing them.",
    ),
    definition(
        "rental-notice",
        "Rental Notice",
        "Property",
        "Create a clear notice for a tenant or landlord regarding a property matter.",
        "3–5 minutes",
        [
            field("document_title", "Document title", required=True),
            field("sender", "Sender", required=True),
            field("recipient", "Recipient", required=True),
            field("property_address", "Property address", "textarea", True),
            field(
                "notice_type",
                "Notice type",
                "select",
                True,
                options=[
                    "Repair request",
                    "Move-out notice",
                    "Payment notice",
                    "Lease renewal",
                    "Other",
                ],
            ),
            field("notice_date", "Notice date", "date", True),
            field("delivery_date", "Delivery date", "date", False),
            field("event_date", "Relevant event date", "date", False),
            field("message", "Notice message", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Notice and parties",
            "Property",
            "Requested action or event",
            "Supporting details",
            "Delivery and response",
            "Reservation of rights",
        ],
        "Keep the notice factual and specific. Do not assert a legal deadline without jurisdiction-specific confirmation; include a reminder to verify notice timing and delivery rules.",
    ),
    definition(
        "property-handover-checklist",
        "Property Handover Checklist",
        "Property",
        "Document the condition, keys, utilities, and outstanding items at a property handover.",
        "5 minutes",
        [
            field("document_title", "Document title", required=True),
            field("property_address", "Property address", "textarea", True),
            field("handover_date", "Handover date", "date", True),
            field("landlord", "Landlord or outgoing party", required=True),
            field("tenant", "Incoming party", required=True),
            field("condition", "Condition summary", "textarea", True),
            field("keys", "Keys and access devices", "textarea", True),
            field("meters", "Meter readings", "textarea", True),
            field("outstanding", "Outstanding items", "textarea", False),
        ],
        [
            "Property and parties",
            "Condition record",
            "Keys and access",
            "Utilities and meters",
            "Outstanding items",
            "Acknowledgements",
        ],
        "Create a practical handover record with space for objective condition notes and signatures. Avoid conclusions about deposits or responsibility beyond the information provided.",
    ),
    definition(
        "freelance-service-agreement",
        "Freelance Service Agreement",
        "Freelancing",
        "Define freelance services, deliverables, fees, revisions, and ownership of work product.",
        "8–12 minutes",
        [
            field("document_title", "Document title", required=True),
            field("freelancer", "Freelancer", required=True),
            field("client", "Client", required=True),
            field("services", "Services", "textarea", True),
            field("deliverables", "Deliverables", "textarea", True),
            field("start_date", "Start date", "date", True),
            field("deadline", "Deadline", "date", False),
            field("fee", "Project fee", "number", True),
            field("revisions", "Included revisions", "number", False, placeholder="2"),
            field(
                "payment_terms",
                "Payment terms",
                "select",
                True,
                options=["50% upfront", "On completion", "Net 15", "Net 30", "Custom"],
            ),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Services and deliverables",
            "Schedule and revisions",
            "Fees and payment",
            "Client responsibilities",
            "Work product",
            "Cancellation and termination",
            "General terms",
        ],
        "Draft a freelancer agreement with a bounded scope, revision count, payment trigger, cancellation treatment, and clear work-product language. Avoid conflating independent contracting with employment.",
    ),
    definition(
        "consulting-agreement",
        "Consulting Agreement",
        "Freelancing",
        "Set out a consulting engagement, objectives, fees, confidentiality, and engagement terms.",
        "8–12 minutes",
        [
            field("document_title", "Document title", required=True),
            field("consultant", "Consultant", required=True),
            field("client", "Client", required=True),
            field("objective", "Engagement objective", "textarea", True),
            field("services", "Services", "textarea", True),
            field("start_date", "Start date", "date", True),
            field("end_date", "End date", "date", False),
            field("fees", "Fees and expenses", "textarea", True),
            field("confidentiality", "Confidentiality expectations", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Engagement",
            "Objectives and services",
            "Fees and expenses",
            "Client dependencies",
            "Confidentiality and IP",
            "Term and termination",
            "General terms",
        ],
        "Create a consulting agreement that distinguishes advice from a guaranteed result and includes practical reliance, deliverable, expense, and termination mechanics.",
    ),
    definition(
        "project-scope-agreement",
        "Project Scope Agreement",
        "Freelancing",
        "Capture project scope, assumptions, deliverables, dependencies, and change control.",
        "6–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("provider", "Provider", required=True),
            field("client", "Client", required=True),
            field("project", "Project", required=True),
            field("objectives", "Objectives", "textarea", True),
            field("deliverables", "Deliverables", "textarea", True),
            field("exclusions", "Out of scope", "textarea", True),
            field("assumptions", "Assumptions and dependencies", "textarea", True),
            field("timeline", "Timeline", "textarea", True),
            field("budget", "Budget", "number", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Project",
            "In scope",
            "Out of scope",
            "Assumptions and dependencies",
            "Timeline and acceptance",
            "Changes",
            "Fees",
            "Signatures",
        ],
        "Write a scope document that makes boundaries and change requests unambiguous. Keep acceptance and dependencies tied to observable project facts.",
    ),
    definition(
        "payment-agreement",
        "Payment Agreement",
        "Freelancing",
        "Document a payment obligation, schedule, security, and default consequences.",
        "6–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("creditor", "Creditor or payee", required=True),
            field("debtor", "Debtor or payer", required=True),
            field("principal", "Principal amount", "number", True),
            field(
                "currency",
                "Currency",
                "select",
                True,
                options=["USD", "EUR", "GBP", "CAD", "AUD", "Other"],
            ),
            field("payment_schedule", "Payment schedule", "textarea", True),
            field("due_date", "Due date", "date", False),
            field("late_interest", "Late-payment treatment", "textarea", False),
            field("security", "Security or guarantee", "textarea", False),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Parties and amount",
            "Payment schedule",
            "Due date and method",
            "Late payment",
            "Security",
            "Costs and notices",
            "Default and general terms",
        ],
        "Draft a general payment agreement using the stated currency and amount. Do not invent an interest rate or security interest; flag those for review when absent.",
    ),
    definition(
        "invoice-payment-terms",
        "Invoice and Payment Terms",
        "Freelancing",
        "Create invoice details and clear payment terms for a client transaction.",
        "4–6 minutes",
        [
            field("document_title", "Document title", required=True),
            field("issuer", "Issuer", required=True),
            field("recipient", "Recipient", required=True),
            field("invoice_number", "Invoice number", required=True),
            field("issue_date", "Issue date", "date", True),
            field("due_date", "Payment due date", "date", True),
            field("items", "Services or items", "textarea", True),
            field("subtotal", "Subtotal", "number", True),
            field("tax", "Tax or fees", "number", False),
            field("total", "Total due", "number", True),
            field("payment_method", "Payment method", "textarea", True),
        ],
        [
            "Invoice details",
            "Services and amounts",
            "Payment terms",
            "Disputes and late payment",
            "Notes",
        ],
        "Create a practical invoice record with totals reconciled to the provided inputs. Clearly state that the invoice is not a substitute for tax or legal advice.",
    ),
    definition(
        "authorization-letter",
        "Authorization Letter",
        "Personal",
        "Give another person permission to act on your behalf for a defined purpose.",
        "4–6 minutes",
        [
            field("document_title", "Document title", required=True),
            field("authorizer", "Authorizer", required=True),
            field("representative", "Authorized representative", required=True),
            field("purpose", "Authorized purpose", "textarea", True),
            field("scope", "Scope of authority", "textarea", True),
            field("start_date", "Start date", "date", True),
            field("end_date", "End date", "date", False),
            field(
                "identity_details",
                "Identity or account details",
                "textarea",
                False,
                help_text="Use only the minimum identifying information needed",
            ),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Authorization",
            "Scope and purpose",
            "Term",
            "Responsibilities",
            "Revocation",
            "Governing terms",
            "Signatures",
        ],
        "Keep authority narrow and purpose-specific. Avoid requesting passwords or unnecessary sensitive identifiers, and state that the representative must verify the scope with the receiving organization.",
    ),
    definition(
        "affidavit-draft",
        "Affidavit Draft Template",
        "Personal",
        "Organize a factual sworn statement for review before it is sworn or signed.",
        "10–15 minutes",
        [
            field("document_title", "Document title", required=True),
            field("deponent", "Deponent", required=True),
            field("capacity", "Capacity or relationship", "textarea", True),
            field("jurisdiction", "Court or authority", "textarea", True),
            field("facts", "Factual statements", "textarea", True),
            field("dates", "Relevant dates", "textarea", True),
            field("witness", "Witness information", "textarea", False),
            field("notary", "Notary or official information", "textarea", False),
        ],
        [
            "Caption and deponent",
            "Statement of facts",
            "Dates and exhibits",
            "Requested relief",
            "Verification and signature",
            "Filing note",
        ],
        "Organize facts without inventing allegations or legal conclusions. Clearly flag that affidavit formalities, penalties for false statements, and filing requirements must be confirmed by qualified counsel or the relevant official.",
    ),
    definition(
        "general-agreement",
        "General Agreement",
        "Personal",
        "Create a flexible written agreement for a defined exchange or arrangement.",
        "6–10 minutes",
        [
            field("document_title", "Document title", required=True),
            field("party_one", "First party", required=True),
            field("party_two", "Second party", required=True),
            field("purpose", "Purpose of agreement", "textarea", True),
            field("obligations_one", "First party obligations", "textarea", True),
            field("obligations_two", "Second party obligations", "textarea", True),
            field("payment", "Payment or consideration", "textarea", False),
            field("term", "Term", "textarea", True),
            field("termination", "Termination", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Purpose",
            "Parties",
            "Obligations",
            "Consideration",
            "Term and termination",
            "Confidentiality and IP",
            "Dispute resolution",
            "General terms",
        ],
        "Use only clauses relevant to the stated arrangement, mark optional protections, and avoid generic provisions that could conflict with the parties' actual deal.",
    ),
    definition(
        "loan-agreement",
        "Loan Agreement",
        "Personal",
        "Record the parties, amount, repayment, interest, and default terms of a loan.",
        "8–12 minutes",
        [
            field("document_title", "Document title", required=True),
            field("lender", "Lender", required=True),
            field("borrower", "Borrower", required=True),
            field("principal", "Loan amount", "number", True),
            field(
                "currency",
                "Currency",
                "select",
                True,
                options=["USD", "EUR", "GBP", "CAD", "AUD", "Other"],
            ),
            field("advance_date", "Advance date", "date", True),
            field("repayment_date", "Repayment date", "date", True),
            field("interest", "Interest terms", "textarea", True),
            field("security", "Collateral or security", "textarea", False),
            field("default", "Default remedies", "textarea", True),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Loan amount and purpose",
            "Disbursement",
            "Repayment and interest",
            "Representations",
            "Security",
            "Default and enforcement",
            "Notices and general terms",
        ],
        "Draft a general loan agreement, preserving the stated economics and flagging interest, usury, collateral, and enforcement rules for local legal review. Never assume a security interest is valid.",
    ),
    definition(
        "consent-letter",
        "Consent Letter",
        "Personal",
        "Record a specific permission or consent for an action involving another person or organization.",
        "4–6 minutes",
        [
            field("document_title", "Document title", required=True),
            field("consenting_party", "Consenting party", required=True),
            field("beneficiary", "Person receiving consent", required=True),
            field("context", "Context for consent", "textarea", True),
            field("consent_scope", "What is consented to", "textarea", True),
            field("conditions", "Conditions or limitations", "textarea", True),
            field("effective_date", "Effective date", "date", True),
            field("expiry", "Expiry or revocation", "textarea", False),
            field("governing_law", "Governing law", required=True),
        ],
        [
            "Consent and parties",
            "Context",
            "Scope of consent",
            "Conditions",
            "Duration and revocation",
            "Acknowledgement",
        ],
        "Make the consent specific, limited, and revocable where appropriate. Avoid language that grants authority beyond the stated purpose or waives rights unknowingly.",
    ),
]


TEMPLATE_INDEX = {item["slug"]: item for item in TEMPLATE_DEFINITIONS}


def get_definition(slug: str) -> dict[str, Any] | None:
    value = TEMPLATE_INDEX.get(slug)
    return deepcopy(value) if value else None
