import { CheckCircle2, FileSearch, LockKeyhole, MessageCircle, Sparkles } from 'lucide-react';
import { PublicShell } from '@/components/legal/public-shell';
import { SectionHeading } from '@/components/legal/marketing';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

const steps = [
  { icon: FileSearch, title: 'Find a useful starting point', text: 'Search the template library and select the document that matches your situation.' },
  { icon: MessageCircle, title: 'Share the relevant context', text: 'A short, structured form asks for the parties, dates, scope, and decisions that matter.' },
  { icon: Sparkles, title: 'Generate a first draft', text: 'Gemini creates a structured draft that clearly labels assumptions and missing information.' },
  { icon: CheckCircle2, title: 'Edit, export, and review', text: 'Refine the document in the editor, keep versions, and export a PDF or DOCX when ready.' },
];
export default function HowItWorksPage() { return <PublicShell><div className="container-shell py-16 sm:py-24"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">How it works</p><h1 className="mt-4 font-display text-4xl leading-[1.12] tracking-tight sm:text-5xl">A guided path from uncertainty to a useful draft.</h1><p className="mt-5 text-lg leading-8 text-muted">LegalEase keeps the workflow focused so you can spend your energy on the decisions that need your judgment.</p></div><div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map((step, index) => <Card key={step.title} className="p-6"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-forest/10 text-forest"><step.icon className="h-5 w-5" /></span><span className="font-mono text-xs font-bold text-muted">0{index + 1}</span></div><h2 className="mt-6 text-lg font-bold">{step.title}</h2><p className="mt-3 text-sm leading-6 text-muted">{step.text}</p></Card>)}</div><div className="mx-auto mt-16 max-w-3xl"><SectionHeading eyebrow="Designed for trust" title="The useful boundary is clear." description="AI can help you see structure and wording. It cannot know every fact, local rule, or future dispute. LegalEase makes that boundary visible throughout the experience." /><div className="mt-8 grid gap-4 sm:grid-cols-3"><Card className="p-5"><LockKeyhole className="h-5 w-5 text-forest" /><h3 className="mt-4 font-bold">Private workspace</h3><p className="mt-2 text-sm leading-6 text-muted">Signed-in users get ownership-protected document access.</p></Card><Card className="p-5"><Sparkles className="h-5 w-5 text-forest" /><h3 className="mt-4 font-bold">Structured AI</h3><p className="mt-2 text-sm leading-6 text-muted">Prompts are controlled and outputs are validated before saving.</p></Card><Card className="p-5"><FileSearch className="h-5 w-5 text-forest" /><h3 className="mt-4 font-bold">Clear review</h3><p className="mt-2 text-sm leading-6 text-muted">Findings are prompts for questions, not legal conclusions.</p></Card></div><div className="mt-10 text-center"><Link href="/register"><Button size="lg">Create your workspace</Button></Link></div></div></div></PublicShell>; }
