import Link from 'next/link';
import { Check, Sparkles } from 'lucide-react';
import { PublicShell } from '@/components/legal/public-shell';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

const plans = [{ name: 'Starter', price: 'Free', text: 'For exploring the workspace and preparing a first draft.', features: ['24 guided templates', 'Private document workspace', 'AI-assisted drafting in mock or configured mode', 'PDF and DOCX export', 'Version history'] }, { name: 'Professional', price: 'Coming soon', text: 'For teams that want more control and collaboration.', features: ['Everything in Starter', 'Team workspaces', 'Advanced review workflows', 'Usage controls', 'Priority support'] }];
export default function PricingPage() { return <PublicShell><div className="container-shell py-16 sm:py-24"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">Simple, transparent pricing</p><h1 className="mt-4 font-display text-4xl leading-[1.12] tracking-tight sm:text-5xl">Start with clarity.</h1><p className="mt-5 text-lg leading-8 text-muted">Use the core LegalEase workspace at no cost. We are designing team plans thoughtfully rather than hiding complexity behind a trial.</p></div><div className="mx-auto mt-14 grid max-w-4xl gap-5 md:grid-cols-2">{plans.map((plan, index) => <Card key={plan.name} className={index === 0 ? 'border-forest/40 shadow-lift' : ''}><CardContent className="p-7 sm:p-9">{index === 0 ? <Badge>Available now</Badge> : <Badge variant="muted">Coming soon</Badge>}<h2 className="mt-5 text-2xl font-bold">{plan.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted">{plan.text}</p><p className="mt-6 text-4xl font-extrabold tracking-tight">{plan.price}</p>{index === 0 ? <p className="mt-1 text-xs text-muted">No credit card required</p> : <p className="mt-1 text-xs text-muted">We will announce details when available</p>}<ul className="mt-8 space-y-3 border-t border-border pt-6">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-muted"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />{feature}</li>)}</ul><Link href={index === 0 ? '/register' : '/contact'} className="mt-8 block"><Button className="w-full" variant={index === 0 ? 'primary' : 'secondary'}>{index === 0 ? 'Create free account' : 'Contact us'} <Sparkles className="h-4 w-4" /></Button></Link></CardContent></Card>)}</div><p className="mx-auto mt-8 max-w-2xl text-center text-xs leading-6 text-muted">AI features may require a configured AI provider and can involve third-party processing. LegalEase does not guarantee that generated content is complete, valid, enforceable, or compliant.</p></div></PublicShell>; }
